services
  - type web
    name practicas-api
    env docker
    plan free
    rootDir backend
    envVars
      - key NODE_ENV
        value production
      - key PORT
        value 4000
      - key JWT_SECRET
        value super_secreto_2025
      - key JWT_EXPIRES_IN
        value 1d
      - key CORS_ORIGIN
        value 
      - key DATABASE_URL
        fromDatabase
          name practicas-db
          property connectionString

  - type web
    name practicas-web
    env docker
    plan free
    rootDir frontend
    envVars
      - key VITE_API_URL
        value httpspracticas-api.onrender.com

databases
  - name practicas-db
    plan free
